_BASE_: "Base-FasterRCNN_R34_C4.yaml"
OUTPUT_DIR: "miccai_outputs/FasterRCNN/fold0_iter5k"
SOLVER:
  SEGS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (3000, 4000)
  MAX_ITER: 5000
  WARMUP_ITERS: 100
  OPTIMIZER: "ADAMW"
  ADAM_BETA: (0.9, 0.99)
TEST:
  EVAL_PERIOD: 5000