MODEL:
  WEIGHTS: "pretrained_models/r34.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "TemporalProposalNetwork"
  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 2
  RESNETS:
    DEPTH: 34
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 64
  PROPOSAL_GENERATOR:
    NAME: "YOLOXHead"
  YOLOX:
    IN_FEATURES: [ "res4" ]
    STRIDES: [ 16 ]
    NMS_THRESH_TEST: 0.7
    NMS_TYPE: "normal"
    PRE_NMS_TOPK: 256
    NUM_PROPOSALS: 16
DATASETS:
  NUM_FOLDS: 4
  TEST_FOLDS: (0,)
  SUFFIX: "_cva_new"
  FRAMESAMPLER: "FrameSampler"
INPUT:
  FIXED_AREA_TRAIN: 900000
  FIXED_AREA_TEST: 900000
  FORMAT: "RGB"
  SCALE_TRAIN: (0.3, 1.5)
  SCALE_TEST: 1.0
  TRAIN_FRAME_SAMPLER:
    INTERVAL: 30
    NUM_OUT_FRAMES: 16
DATALOADER:
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "IsolateTrainingSampler"
SOLVER:
  SEGS_PER_BATCH: 8
  BASE_LR: 0.0002
  STEPS: (6000, 8000)
  MAX_ITER: 10000
  WARMUP_ITERS: 1000
  OPTIMIZER: "ADAMW"
  ADAM_BETA: (0.9, 0.99)
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "value"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 10000
VERSION: 2