MODEL:
  WEIGHTS: "pretrained_models/r34.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "MEGA"
  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 2
  RESNETS:
    DEPTH: 34
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 64
    HALF_CHANNEL: True
  PROPOSAL_GENERATOR:
    NAME: "RPNWithMem"
  RPN:
    IN_FEATURES: ["res4"]
    PRE_NMS_TOPK_TRAIN: 256
    PRE_NMS_TOPK_TEST: 256
    POST_NMS_TOPK_TRAIN: 16
    POST_NMS_TOPK_TEST: 16
  ANCHOR_GENERATOR:
    ASPECT_RATIOS: [[0.33, 0.5, 0.66, 1.0, 2.0, 3.0]]
    SIZES: [[32, 64, 128, 256, 512]]
  ROI_HEADS:
    NAME: "MEGAHeads"
    IN_FEATURES: ["res4"]
    PROPOSAL_APPEND_GT: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    INTERVAL_PRE_TEST: 15
    INTERVAL_AFTER_TEST: 0
DATASETS:
  NUM_FOLDS: 4
  TEST_FOLDS: (0,)
  SUFFIX: "_cva_new"
  FRAMESAMPLER: "MemoryFrameSampler"
INPUT:
  FORMAT: "RGB"
  SCALE_TRAIN: (0.3, 1.5)
  SCALE_TEST: 1.0
  TRAIN_FRAME_SAMPLER:
    INTERVAL: 20
    MEMORY_INTERVAL: 10
    NUM_OUT_FRAMES: 10
    MEMORY_FRAMES: 6 # 10 + 6 = 16
  FIXED_AREA_TRAIN: 900000
  FIXED_AREA_TEST: 900000
DATALOADER:
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "IsolateTrainingSampler"
SOLVER:
  SEGS_PER_BATCH: 8
  BASE_LR: 0.002
  STEPS: (6000, 8000)
  MAX_ITER: 10000
  WARMUP_ITERS: 1000
  OPTIMIZER: "ADAMW"
  ADAM_BETA: (0.9, 0.99)
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "value"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 10000
VERSION: 2
