MODEL:
  WEIGHTS: "pretrained_models/r34.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  META_ARCHITECTURE: "TransVOD"
  BACKBONE:
    NAME: "build_resnet_backbone"
    FREEZE_AT: 2
  RESNETS:
    DEPTH: 34
    STRIDE_IN_1X1: False
    RES2_OUT_CHANNELS: 64
  DeformableDETR:
    POS_EMBED_TYPE: "sine"
    NUM_CLASSES: 1
    IN_FEATURES: ["res4"]
    TWO_STAGE: False
    NUM_FEATURE_LEVELS: 1
    HIDDEN_DIM: 256
    NHEADS: 8
    ENCODER_LAYERS: 2
    DECODER_LAYERS: 4
    DIM_FEEDFORWARD: 512
    DROPOUT: 0.1
    DECODER_N_POINTS: 4
    ENCODER_N_POINTS: 4
    NUM_QUERIES: 16
    WITH_BOX_REFINE: True
    CLASS_WEIGHT: 2.0
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    AUX_LOSS: True
    NMS_THRESH: 0.7
    USE_NMS: True
    USE_TEMPORAL_ENCODER: False
    QUERY_ENCODER_LAYERS: 2
    TEMPORAL_DECODER_LAYERS: 1
DATASETS:
  NUM_FOLDS: 4
  TEST_FOLDS: (0,)
  SUFFIX: "_cva_new"
  FRAMESAMPLER: "FrameSampler"
INPUT:
  FIXED_AREA_TRAIN: 900000
  FIXED_AREA_TEST: 900000
  FORMAT: "RGB"
  SCALE_TRAIN: (0.3, 1.5)
  SCALE_TEST: 1.0
  TRAIN_FRAME_SAMPLER:
    INTERVAL: 30
    NUM_OUT_FRAMES: 16
DATALOADER:
  NUM_WORKERS: 4
  SAMPLER_TRAIN: "IsolateTrainingSampler"
SOLVER:
  SEGS_PER_BATCH: 8
  BASE_LR: 0.0002
  WEIGHT_DECAY: 0.0001
  STEPS: (6000, 8000)
  MAX_ITER: 10000
  WARMUP_ITERS: 1000
  OPTIMIZER: "ADAMW"
  ADAM_BETA: (0.9, 0.99)
  LR_MULTIPLIER_NAME: ("backbone", "reference_points", "sampling_offsets")
  LR_MULTIPLIER_VALUE: (0.1, 0.1, 0.1)
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "value"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0
TEST:
  EVAL_PERIOD: 10000
VERSION: 2
